services:
    customer.query.create_customer:
        class: Application\Command\Customer\CustomerQuery
        arguments:
          - '@customer.repository.customer'

    customer.handler.create_customer:
        class: Application\Command\Customer\CreateCustomerHandler
        arguments:
          - '@customer.repository.customer'
        tags:
            - { name: tactician.handler, command: Application\Command\Customer\CreateCustomerCommand }