services:
    customer.use_case.customer:
        class: Application\UseCase\Customer\CustomerCommand
        arguments:
          - '@customer.repository.customer'

    customer.use_case.customer_query:
        class: Application\UseCase\Customer\CustomerQuery
        arguments:
          - '@customer.repository.customer'